# Generated by Django 2.2.1 on 2019-08-06 06:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('home', '0001_initial'), ('home', '0002_auto_20190609_0004'), ('home', '0003_auto_20190612_0742'), ('home', '0004_auto_20190612_0823'), ('home', '0005_reservation_date'), ('home', '0006_auto_20190614_2336'), ('home', '0007_auto_20190616_0700'), ('home', '0008_auto_20190616_0723'), ('home', '0009_auto_20190616_0724'), ('home', '0010_auto_20190616_0724'), ('home', '0011_auto_20190621_1858'), ('home', '0012_place_staging'), ('home', '0013_auto_20190803_1950'), ('home', '0014_place_staging_requested_by_user')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_en', models.TextField(blank=True)),
                ('city', models.TextField()),
                ('cuisine', models.TextField(blank=True)),
                ('hours', models.TextField(blank=True)),
                ('english_friendly', models.BooleanField(blank=True)),
                ('outdoor_seating', models.BooleanField(blank=True)),
                ('website', models.TextField(blank=True)),
                ('menu', models.TextField(blank=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='place',
            table='planet_osm_point',
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('requested_by_user', models.TextField()),
                ('name_reservation', models.TextField()),
                ('name_restaurant', models.TextField()),
                ('party_size', models.IntegerField()),
                ('time', models.TimeField()),
                ('caller', models.TextField(blank=True)),
                ('request_completed', models.BooleanField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('phone', models.TextField(default='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'permissions': (('can_accept_calls', 'can accept calls'),),
            },
        ),
        migrations.CreateModel(
            name='place_staging',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('way', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('requested_by_user', models.TextField(default='anon')),
            ],
        ),
    ]
