# Generated by Django 2.2.1 on 2019-06-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190612_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='request_completed',
            field=models.BooleanField(),
        ),
    ]
