# Generated by Django 2.2.1 on 2019-06-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_reservation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': (('can_accept_calls', 'can accept calls'),)},
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.TextField(default=''),
        ),
        migrations.AlterModelTable(
            name='place',
            table='planet_osm_point',
        ),
    ]
