# Generated by Django 2.2.1 on 2019-06-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190616_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='uuid',
            field=models.TextField(editable=False),
        ),
    ]
