# Generated by Django 2.2.1 on 2019-06-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190616_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='uuid',
            field=models.TextField(editable=False),
        ),
    ]
