# Generated by Django 2.2.1 on 2019-08-03 19:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190621_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='place_staging',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_en', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('cuisine', models.TextField(blank=True)),
                ('opening_hours', models.TextField(blank=True)),
                ('outdoor_seating', models.BooleanField(blank=True)),
                ('website', models.TextField(blank=True)),
                ('phone', models.TextField()),
                ('way', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
