# Generated by Django 2.2.1 on 2019-08-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190803_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_staging',
            name='requested_by_user',
            field=models.TextField(default='anon'),
        ),
    ]
